//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxProxy.XDomainServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XDomainServiceReference.IXDomainService")]
    public interface IXDomainService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXDomainService/DoWork1", ReplyAction="http://tempuri.org/IXDomainService/DoWork1Response")]
        string DoWork1(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXDomainService/DoWork1", ReplyAction="http://tempuri.org/IXDomainService/DoWork1Response")]
        System.Threading.Tasks.Task<string> DoWork1Async(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXDomainService/DoWork2", ReplyAction="http://tempuri.org/IXDomainService/DoWork2Response")]
        string DoWork2(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXDomainService/DoWork2", ReplyAction="http://tempuri.org/IXDomainService/DoWork2Response")]
        System.Threading.Tasks.Task<string> DoWork2Async(string json);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXDomainServiceChannel : AjaxProxy.XDomainServiceReference.IXDomainService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XDomainServiceClient : System.ServiceModel.ClientBase<AjaxProxy.XDomainServiceReference.IXDomainService>, AjaxProxy.XDomainServiceReference.IXDomainService {
        
        public XDomainServiceClient() {
        }
        
        public XDomainServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XDomainServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XDomainServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XDomainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork1(string json) {
            return base.Channel.DoWork1(json);
        }
        
        public System.Threading.Tasks.Task<string> DoWork1Async(string json) {
            return base.Channel.DoWork1Async(json);
        }
        
        public string DoWork2(string json) {
            return base.Channel.DoWork2(json);
        }
        
        public System.Threading.Tasks.Task<string> DoWork2Async(string json) {
            return base.Channel.DoWork2Async(json);
        }
    }
}
